// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMtEnbKS3xDJ4t64JDxLzbcsKyIBXwo_Y',
    appId: '1:111801931523:web:eb91432df2cd3f50eabb36',
    messagingSenderId: '111801931523',
    projectId: 'learning-a5dc6',
    authDomain: 'learning-a5dc6.firebaseapp.com',
    storageBucket: 'learning-a5dc6.appspot.com',
    measurementId: 'G-PHTJ706P5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdlDFtiE06H4MAuFQNMnvDJZIE1fBSzKc',
    appId: '1:111801931523:android:905c35092977447deabb36',
    messagingSenderId: '111801931523',
    projectId: 'learning-a5dc6',
    storageBucket: 'learning-a5dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fdKGxIHXkqbxUng0011UNOYFPaZ-pyo',
    appId: '1:111801931523:ios:94d0b807e488ff6feabb36',
    messagingSenderId: '111801931523',
    projectId: 'learning-a5dc6',
    storageBucket: 'learning-a5dc6.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_fdKGxIHXkqbxUng0011UNOYFPaZ-pyo',
    appId: '1:111801931523:ios:711a5df3af177c2ceabb36',
    messagingSenderId: '111801931523',
    projectId: 'learning-a5dc6',
    storageBucket: 'learning-a5dc6.appspot.com',
    iosBundleId: 'com.example.learning.RunnerTests',
  );
}
